# Generated by Django 2.2.4 on 2019-08-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='phone_no',
            field=models.CharField(default='None', max_length=12),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='blogger_group',
            field=models.CharField(max_length=50),
        ),
    ]
