# Generated by Django 2.2.4 on 2019-08-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20190807_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={},
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('upload_img', models.ImageField(upload_to='images/blog_pic/')),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.Blogger')),
            ],
        ),
    ]
