# Generated by Django 2.2.4 on 2019-08-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_auto_20190807_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='following',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_blogger_following_+', to='blogpost.Blogger'),
        ),
    ]
