# Generated by Django 2.2.4 on 2019-08-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_blogger_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='following',
            field=models.ManyToManyField(default=None, related_name='_blogger_following_+', to='blogpost.Blogger'),
        ),
    ]
